#!/bin/bash

function usage {
  echo "Usage: $(basename "$0") directory find replace"
}

if [[ $# -lt 3 ]]; then
  usage
  exit 1;
fi

find "$1" -name "${2}*" | while read -r f
do
  mv "$f" "${f/${2}/${3}}"
  if [[ $? -ne 0 ]]; then
    echo "Failed renaming $f"
    exit 1;
  fi
  echo "mv $f -> ${f/${2}/${3}}"
done
